config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#index'

  devise_scope :user do
    post 'users/sign_up', to: 'registrations#create', as: :create_registrations
    put 'users/edit', to: 'registrations#update', as: :edit_registrations
  end

  resources :profiles, only: [:show], param: :username, path: '/'

  resources :projects

  resources :projects do
    resources :likes
    resources :comments, only: %i[create destroy]
  end

  resources :follows, only: %i[create destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < AuthorizationsController
  before_action :set_comment

  def create
    @comment = current_user.comments.new(comment_params)

    if @comment.save
      flash[:notice] = 'Comment created'
    else
      flash[:alert] = 'Comment cannot be created'
    end

    redirect_to project_path(params[:project_id])
  end

  def destroy
    if @comment.present?
      if @comment.destroy
        flash[:notice] = 'Comment deleted'
      else
        flash[:alert] = 'Comment cannot be deleted'
      end
    else
      flash[:alert] = 'Comment not found'
    end

    redirect_to project_path(params[:project_id])
  end

  private

  def set_comment
    @comment = current_user.comments.find_by_id(params[:id])
  end

  def comment_params
    params
      .require(:comment)
      .permit(:content)
      .merge(project_id: params[:project_id])
  end
end

app/views/comments/_comment.html.erb
 <div class="card project_comments_card">
    <div class="project_comments">
      <%= link_to profile_path(comment.user) do %>
        <%= image_tag comment.user.profile_img, class: "user_profile_image smaller" %>
      <% end %>
      <div class="project_comments_info">
        <div class="flex_row">
          <%= link_to profile_path(comment.user) do %>
            <h4> <%= comment.user.full_name %></h4> 
          <% end %>
          <small> • <%= comment.created_at.to_date %> </small>
          <div class="last_child">
          <% if user_signed_in? %>
            <% if comment.user.id == current_user.id %>
              <%= link_to project_comment_path(@project, comment), method: :delete, data: { confirm: "Are you sure about deleting the comment?" }, class: "button_close" do %>
                <i class="fas fa-times"></i>
              <% end %>
            <% end %>
          <% end %>
          </div>
        </div>
        <p> <%= comment.content %> </p>
      </div>
    </div>
</div>

app/views/comments/_form.html.erb
 <div>
    <div class="project_comments">
         <div class="card project_comments_card">
          <%= image_tag current_user.profile_img, class: "user_profile_image smaller" %>
            <div class="full_width">
            <%= form_for(@project, url: project_comments_path(@project), method: :post) do |f| %>
                <%= render "devise/shared/error_messages", resource: @project %>
                
                <div class="field comments_box">
                  <h4><%= f.label :comment %></h4>
                  <textarea class="project_comments text_area" placeholder = "What are your thoughts on this project?" name="comment[content]" required></textarea>
                </div>

                <div class="flex_direction_rows_reverse">
                <%= f.submit "Post a comment" %>
                </div>
            <% end %>
            </div>
        </div>
    </div>
</div>