config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#index'

  devise_scope :user do
    post 'users/sign_up', to: 'registrations#create', as: :create_registrations
    put 'users/edit', to: 'registrations#update', as: :edit_registrations
  end

  resources :profiles, only: [:show], param: :username, path: '/'

  resources :projects

  resources :projects do
    resources :likes
    resources :comments, only: %i[create destroy]
  end

  resources :follows, only: %i[create destroy]
end

app/views/partials/_nav.html.erb
<nav class="main_navbar">
  <ul>
    <li class="nav_item">
      <%= link_to "Behanc.io", root_path, class: "nav-link" %>
    </li>

    <% if user_signed_in? %>
      <li class="nav_item">
        <%= link_to "Profile", profile_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav_item">
        <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav_item navbar_last_child">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
    <% else %>
      <li class="nav_item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/partials/_new_project_card.html.erb
<div class="create_project_card">
  <% if user_signed_in? %>
    <div>
      <%= link_to "Create a Project", new_project_path, class: "basic_button" %>
    </div>
  <% end %>  
   
  <p>Show your talent to the world</p>
</div>