config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  devise_for :users, controllers: { registrations: 'registrations' }
  root to: 'home#index'

  devise_scope :user do
    post 'users/sign_up', to: 'registrations#create', as: :create_registrations
    put 'users/edit', to: 'registrations#update', as: :edit_registrations
  end

  resources :profiles, only: [:show], param: :username, path: '/'

  resources :projects

  resources :projects do
    resources :likes
    resources :comments, only: %i[create destroy]
  end

  resources :follows, only: %i[create destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  has_rich_text :content
  has_one_attached :cover_image

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  default_scope { order(created_at: :desc) }

  CATEGORIES = ['Graphic Design', 'Illustration', 'Photography', 'Interaction Design', 'Fashion', 'Product Design', 'Architecture', 'Advertising'].freeze

  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :content, presence: true
  validates :cover_image, content_type: ['image/jpeg', 'image/png', 'image/jpg'], presence: true
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_project

  def show
    redirect_to root_path, flash: { alert: "The project #{params[:id]} was not found" } unless @project
  end

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = 'Project was successfully created'
      redirect_to project_path(@project)
    else
      flash[:alert] = 'Project was not created'
      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Project was succesfully deleted' }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find_by_id(params[:id])
  end

  protected

  def project_params
    params.require(:project).permit(:title, :description, :category, :cover_image, :content).merge(user_id: current_user.id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: %i[show index]
  before_action :set_project, except: %i[edit update destroy]
  before_action :set_current_user_projects, only: %i[edit update destroy]

  def show
    redirect_to root_path, flash: { alert: "The project #{params[:id]} was not found" } unless @project
  end

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def edit; end

  def create
    @project = Project.new(project_params)

    if @project.save
      flash[:notice] = 'Project was successfully created'
      send_notification_to_followers
      redirect_to project_path(@project)
    else
      flash[:alert] = 'Project was not created'

      render 'new'
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Project was succesfully deleted' }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find_by_id(params[:id])
  end

  def set_current_user_projects
    @project = current_user.projects.find_by_id(params[:id]) or not_found
  end

  def not_found
    redirect_to root_path, alert: 'Not found'
  end

  def send_notification_to_followers
    @project.user.followers.each do |follower|
      ActionCable.server.broadcast("room-#{follower.id}:notification_channel", "#{@project.user.full_name} has published a new project: #{@project.title}! ,#{project_url(@project)}")
    end
  end

  protected

  def project_params
    params.require(:project).permit(:title, :description, :category, :cover_image, :content).merge(user_id: current_user.id)
  end
end

app/views/projects/edit.html.erb
<div class="card">
  <div class="form_container">
    <h1>Update project</h1>

    <%= form_for(@project, url: project_path(@project), method: :put) do |f| %>
      <%= render "devise/shared/error_messages", resource: @project %>
        <div class="field">
          <h4><%= f.label :title %></h4>
          <%= f.text_field :title %>
        </div>
      
        <div class="field">
          <h4><%= f.label :description %></h4>
          <%= f.text_field :description %>
        </div>

        <div class="field">
          <h4><%= f.label :cover_image %></h4>
          <%= f.file_field :cover_image %>
        </div>

        <div class="field">
          <h4><%= f.label :category %></h4>
          
          <fieldset>
            <% Project::CATEGORIES.each do |category| %>
              <div class="category_with_label">
                <%= f.radio_button :category, category %>
                <%= f.label :category, category %>
              </div>
            <% end %>
          </fieldset>
        </div>

        <div>
          <h4><%= f.label :content %></h4>
          <%= f.rich_text_area :content %>
        </div>

        <div class="actions">
          <%= f.submit "Update project" %>
        </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="card">
  <h1>Create a project</h1>

  <%= form_for(@project, url: projects_path, method: :post) do |f| %>
    <%= render "devise/shared/error_messages", resource: @project %>
    
    <div class="field">
      <h4><%= f.label :title %></h4>
      <%= f.text_field :title %>
    </div>
    
    <div class="field">
      <h4><%= f.label :description %></h4>
      <%= f.text_field :description %>
    </div>

    <div class="field">
      <h4><%= f.label :cover_image %></h4>
      <%= f.file_field :cover_image %>
    </div>

    <div class="field">
      <h4><%= f.label :category %></h4>
      
      <fieldset>
        <% Project::CATEGORIES.each do |category| %>
          <div class="category_with_label">
            <%= f.radio_button :category, category %>
            <%= f.label :category, category %>
          </div>
        <% end %>
      </fieldset>
    </div>

    <div>
      <h4><%= f.label :content %></h4>
      <%= f.rich_text_area :content, required: true %>
    </div>

    <div class="actions">
      <%= f.submit "Create project" %>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="card project_show_card">
  <div class="project_content_container">
    <h1> <%= @project.title %></h1>
      <p><%= @project.description %></p>
      <p><%= @project.content %></p>
  </div>
</div>

<div class="card project_bottom_card" id="project_footer">
  <div class="project_footer">
    <% if user_signed_in? %>
      <% pre_like = @project.likes.find { |like| like.user_id == current_user.id } %>
      <% if pre_like %>
        <%= link_to project_like_path(@project, pre_like), class: "basic_button like_button liked_button", method: :delete do %>
          <i class="fas fa-thumbs-up fa-2x"></i>
        <% end %>
      <% else %>
        <%= link_to project_likes_path(@project), class: "basic_button like_button", method: :post do %>
          <i class="fas fa-thumbs-up fa-2x"></i>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "basic_button like_button" do %>
        <i class="fas fa-thumbs-up fa-2x"></i>
      <% end %>
    <% end %>

    <h2> <%= @project.title %></h2>
      <div class="flex_row">
        <div>
          <i class="fas fa-thumbs-up"></i> <%= @project.likes.count %>
        </div>
        <div>
          <i class="fas fa-comment-alt"></i> <%= @project.comments.count %>
        </div>
      </div>
      <p> Published: <%= @project.created_at.to_date %></p>
  </div>
     
  <% if user_signed_in? %>
    <% if @project.user_id == current_user.id %>
      <div class="flex_column">
        <%= link_to "Update project", edit_project_path(@project), class: "basic_button" %>
        <%= link_to "Destroy project", project_path(@project), method: :delete, data: { confirm: "Are you sure?" }, class: "basic_button danger" %>
      </div>
    <% end %>
  <% end %>
  
  <div class="project_comments_container">
    <div class="card project_comments_card">
      <div class="full_width">
        <%= render @project.comments %>
        <% unless user_signed_in? %>
          <div class="card card_without_shadow">
            <h1>Login to join the conversation</h1>
            <%= link_to "Sign up with email", create_registrations_path, class: "basic_button" %>
          </div>
        <% else %>
          <%= render partial: "comments/form" %>
        <% end %>
      </div>
    </div>

    <div>    
      <div class="card project_owner_card">
        <div>
          Owner
        </div>
        <div class="flex_row" >
          <div>
            <%= link_to profile_path(@project.user) do %>
              <%= image_tag @project.user.profile_img, class: "user_profile_image smaller" %>
            <% end %>
          </div>
          <div>
            <%= link_to profile_path(@project.user) do %>
              <h3><%= @project.user.full_name %></h3>
            <% end %>
            <p><i class="fas fa-map-marker-alt"></i> <%= @project.user.location %></p>
          </div>
        </div>
      </div>

      <div class="card project_statistics_card">
        <h3><%= @project.title %></h3>
        <div class="flex_row">
          <div>
            <i class="fas fa-thumbs-up"></i> <%= @project.likes.count %>
          </div>
          <div>
            <i class="fas fa-comment-alt"></i> <%= @project.comments.count %>
          </div>
        </div>
        <p><%= @project.category %></p>
        <p> Published: <%= @project.created_at.to_date %></p>
      </div>
    </div>
  </div>
</div>